### PR TITLE
Update runtime to 23.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
```
/bin/sh: line 1: freetype-config: command not found
ttf2font.c:5:10: fatal error: ft2build.h: No such file or directory
    5 | #include <ft2build.h>
```

That's odd, freetype ought to be in the SDK.

**Comment by bbhtt** [comment]
Runs

**Comment by ghost** [comment]
Is there any progress or error?

**Comment by bbhtt** [comment]
bot, build

**Pull request merged**
